# Generated by Django 3.2 on 2021-05-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShipmentId', models.PositiveBigIntegerField()),
                ('ContainerNr', models.TextField()),
                ('Departure', models.TextField()),
                ('Destination', models.TextField()),
                ('ScheduledDeparture', models.DateTimeField()),
                ('ScheduledArrival', models.DateTimeField()),
                ('RevisedArrival', models.DateTimeField()),
                ('TotalVolume', models.DecimalField(decimal_places=3, max_digits=10000)),
                ('TotalWeight', models.IntegerField()),
                ('Dimensions', models.TextField(blank=True, null=True)),
                ('Carrier', models.TextField()),
                ('ShipperReference', models.TextField()),
            ],
        ),
    ]
