# Generated by Django 3.2 on 2021-05-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='Carrier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='Departure',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='Destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='Dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='ShipperReference',
            field=models.CharField(max_length=20),
        ),
    ]
