# Generated by Django 3.2 on 2021-05-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroundShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNr', models.TextField(max_length=9)),
                ('Status', models.TextField(max_length=20)),
                ('TrackingNr', models.PositiveBigIntegerField()),
                ('Contents', models.TextField(max_length=50)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('Dimensions', models.TextField(max_length=20)),
                ('CollectionCompany', models.TextField(max_length=50)),
                ('CollectionName', models.TextField(max_length=30)),
                ('CollectionAddress', models.TextField(max_length=20)),
                ('CollectionZipCode', models.TextField(max_length=7)),
                ('CollectionCity', models.TextField(max_length=50)),
                ('DeliveryCompany', models.TextField(max_length=50)),
                ('DeliveryName', models.TextField(max_length=30)),
                ('DeliveryAddress1', models.TextField(max_length=20)),
                ('DeliveryAddress2', models.TextField(blank=True, max_length=20, null=True)),
                ('DeliveryZipCode', models.TextField(blank=True, max_length=7, null=True)),
                ('DeliveryCity', models.TextField(max_length=50)),
                ('DeliveryCountryCode', models.TextField(max_length=2)),
                ('Courier', models.TextField(max_length=20)),
                ('CosigneeNr', models.PositiveBigIntegerField()),
                ('ETC', models.DateTimeField()),
                ('ETA', models.DateTimeField()),
            ],
        ),
    ]
