# Generated by Django 3.2 on 2021-05-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundShippingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundshipment',
            name='TrackingNr',
            field=models.TextField(max_length=14),
        ),
    ]
