# Generated by Django 3.2 on 2021-05-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundShippingApp', '0003_alter_groundshipment_cosigneenr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundshipment',
            name='DeliveryCompany',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
