# Generated by Django 3.2 on 2021-05-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundShippingApp', '0005_alter_groundshipment_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundshipment',
            name='Reference',
            field=models.TextField(default=212, max_length=20),
            preserve_default=False,
        ),
    ]
