# Generated by Django 3.2 on 2021-05-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirFreightShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MasterOrder', models.TextField(max_length=50)),
                ('ShipmentNr', models.DecimalField(decimal_places=6, max_digits=15)),
                ('RPShipmentNr', models.TextField(max_length=30)),
                ('SenderName', models.TextField(max_length=100)),
                ('ReceiverName', models.TextField(max_length=100)),
                ('Country', models.TextField(max_length=30)),
                ('City', models.TextField(max_length=30)),
                ('ZipCode', models.TextField(blank=True, max_length=7, null=True)),
                ('CosigneeReference', models.TextField(blank=True, max_length=20, null=True)),
                ('OrderNrCosignee', models.TextField(blank=True, max_length=20, null=True)),
                ('ShipmentInfo', models.TextField(max_length=20)),
                ('ShipmentDate', models.DateField()),
                ('ETD', models.DateField()),
                ('ETA', models.DateField()),
                ('Status', models.TextField()),
            ],
        ),
    ]
