# Generated by Django 3.2 on 2021-05-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirFreightApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airfreightshipment',
            name='ETA',
            field=models.DateField(blank=True, null=True),
        ),
    ]
