# Generated by Django 3.2 on 2021-05-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirFreightApp', '0002_alter_airfreightshipment_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airfreightshipment',
            name='RPShipmentNr',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='airfreightshipment',
            name='ShipmentInfo',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
