# Generated by Django 3.2 on 2021-05-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirFreightApp', '0003_auto_20210513_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airfreightshipment',
            name='ReceiverName',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
