# Generated by Django 3.2 on 2021-05-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirFreightApp', '0004_alter_airfreightshipment_receivername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airfreightshipment',
            name='Country',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
