# Generated by Django 3.2 on 2021-05-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirFreightApp', '0005_alter_airfreightshipment_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airfreightshipment',
            name='City',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='airfreightshipment',
            name='SenderName',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
