# Generated by Django 3.2 on 2021-05-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirFreightApp', '0006_auto_20210513_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airfreightshipment',
            name='ETD',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airfreightshipment',
            name='ShipmentDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
