# Generated by Django 3.2 on 2021-05-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirFreightApp', '0007_auto_20210513_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airfreightshipment',
            name='MasterOrder',
            field=models.TextField(max_length=20),
        ),
    ]
